// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSTranslations
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSTranslations.f56c406f-2cfa-46c3-96fc-dd9d3bfefaca";
        public const string Name = "VSTranslations";
        public const string Description = @"VSIX plugin that allows to translate text parts of the code. This only the core plugin without any translator provider (installed separately).";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Tomas S.";
        public const string Tags = "translations, translator, code, languages";
    }
}
