// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSTranslations
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSTranslationsString = "c7c1ae20-bc53-41bc-8ba1-33a34163f8ee";
        public static Guid VSTranslations = new Guid(VSTranslationsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int VSTranslations_ContextTranslateMenu_TranslateId = 0x0101;
        public const int VSTranslations_ContextTranslateMenu_DeleteTranslationId = 0x0102;
        public const int VSTranslations_TranslationToolbar = 0x1000;
        public const int VSTranslations_TranslationToolbarGroup = 0x1030;
        public const int VSTranslations_TranslationToolbarGroup_FromIndexCombo = 0x0103;
        public const int VSTranslations_TranslationToolbarGroup_FromIndexComboGetList = 0x0104;
        public const int VSTranslations_TranslationToolbarGroup_ToIndexCombo = 0x0105;
        public const int VSTranslations_TranslationToolbarGroup_ToIndexComboGetList = 0x0106;
        public const int VSTranslations_TranslationToolbarGroup_TranslateIcon = 0x0107;
        public const int VSTranslations_TranslationToolbarGroup_TranslationSwap = 0x0108;
        public const int VSTranslations_ContextTranslateMenuGroup = 0x0130;
        public const int VSTranslations_ContextTranslateMenu = 0x0131;
    }
}