// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSTranslations.Plugin.GoogleTranslate
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSTranslations.Plugin.GoogleTranslate.7f2f04a4-acf4-4bb1-b303-a54ad0f7a460";
        public const string Name = "VSTranslations.Plugin.GoogleTranslate";
        public const string Description = @"Google Translate plugin for the core VSTranslations extension.";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Tomas S.";
        public const string Tags = "";
    }
}
