// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSTranslations.Plugin.GoogleTranslate
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSTranslationsPluginGoogleTranslateString = "d307d4ac-b113-4f8e-9411-34384b32c697";
        public static Guid VSTranslationsPluginGoogleTranslate = new Guid(VSTranslationsPluginGoogleTranslateString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {

    }
}