name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
   Configuration: Release

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      configuration: Release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
 
  release:
    needs: build
    uses: ./.github/workflows/release.yml
    with:
      configuration: Release
      semVer: ${{ needs.build.outputs.semVer }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  coverage:
    needs: build
    uses: ./.github/workflows/coverage.yml
    with:
      configuration: Debug
      semVer: ${{ needs.build.outputs.semVer }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}