name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
   Configuration: Debug

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      configuration: Debug
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
