name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
   Configuration: Debug

jobs:
  build:
    # runs-on: windows-latest
    uses: ./.github/workflows/build.yml
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}