name: CI VS Translations

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'maintenence/*'
  pull_request:
    branches:
      - master

jobs:

 build:
    # runs-on: windows-latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x
        dotnet-version: 6.x
        dotnet-quality: ga

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
        vs-prerelease: true

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest

    - name: Restore NuGet
      run: nuget restore VSTranslations.sln

    - name: echo MSBuild
      run: msbuild -version

    - name: Build Solution
      run: |
        msbuild.exe VSTranslations.sln /p:Configuration=Debug /p:Platform="Any CPU"