name: coverage

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
      semVer:
        required: true
        type: string
    secrets:
      token:
        required: true

env:
  SEMVER: ${{ inputs.semVer }}

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
        contents: read
        pages: write
        id-token: write
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: Coverage.${{ env.SEMVER }}
          path: coveragereport/

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './coveragereport'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1